language: perl

perl:
    - "5.18"

before_install:
    - cpanm Dist::Zilla --quiet --notest

install:
    - dzil authordeps | xargs cpanm --quiet --notest
    - dzil listdeps | xargs cpanm --quiet --notest

script:
    - dzil smoke --release
